config/routes.rb
Rails.application.routes.draw do
  get 'pages/terminos', to: 'pages#terminos', as: 'pages_terminos'
  resources :maintenances
  resources :engines
  get 'pages/inicio', to: 'pages#inicio', as: 'pages_inicio'
  resources :maintenances, only: [:show]

  devise_for :users

  # Define la ruta de inicio después de iniciar sesión
  authenticated :user do
    root 'pages#inicio', as: :authenticated_root
  end
  
  # Define la ruta de inicio predeterminada para los no autenticados (inicio de sesión)
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/engine.rb
class Engine < ApplicationRecord
  enum type_engine: {
    'Motor a reacción' => 0,
    'Motor turbohélice' => 1
  }
  has_many :maintenances, dependent: :destroy
#Validaciones.
  validates :name, presence: true, uniqueness: true, format: { with: /\A(REAC|TURBO)-\d+\z/i, message: 'debe seguir el formato REAC-n o TURBO-n' }
  validates :descripcion, presence: true
  validates :type_engine, presence: true
  validates :photo, presence: true
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :authenticate_user!
  before_action only: [:new, :create] do
    authorize_request(["operator", "admin"])
  end
  before_action only: %i[ show edit update destroy ] do
    authorize_request(["admin"])
  end
  # GET /engines or /engines.json
  def index
    @engines = Engine.all
    @pagy, @engines = pagy(@engines)
  end



  # GET /engines/1 or /engines/1.json
  def show
    @engine = Engine.find(params[:id])
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines or /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to engine_url(@engine), notice: "Engine was successfully created." }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1 or /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to engine_url(@engine), notice: "Engine was successfully updated." }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1 or /engines/1.json
  def destroy
    @engine = Engine.find(params[:id])

    if @engine.destroy
      respond_to do |format|
        format.html { redirect_to engines_url, notice: "Engine was successfully destroyed." }
      end
    else
      # Manejar el caso en el que el mantenimiento no pudo ser eliminado
      respond_to do |format|
        format.html { redirect_to engines_url, alert: "Unable to destroy engines." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def engine_params
      params.require(:engine).permit(:type_engine, :maintenance_id)
    end

    def authenticate_admin
      unless current_user && current_user.admin?
        flash[:alert] = "Acceso no autorizado. Debes ser un administrador para realizar esta acción."
        redirect_to engines_path
      end
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_engine.html.erb
<div id="<%= dom_id engine %>">
  <p>
    <strong>Type engine:</strong>
    <%= engine.type_engine %>
  </p>

  <p>


  </p>

</div>

app/views/engines/_form.html.erb
<%= form_with(model: engine) do |form| %>
  <% if engine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
        <% engine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type_engine, style: "display: block" %>
    <%= form.text_field :type_engine %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Ver", @engine %> |
  <%= link_to "Volver", engines_path %>
</div>

app/views/engines/index.html.erb
<h1 class="text-center ">Motores</h1>

<div id="engines">
  <% if notice.present? %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Tipo de motor</th>
        <th>Foto</th>
        <th>Menu</th>
      </tr>
    </thead>
    <tbody>
      <% @engines.each do |engine| %>
        <tr>
          <td><%= engine.name %></td>
          <td><%= engine.descripcion %></td>
          <td><%= engine.type_engine %></td>
          <td><%= image_tag engine.photo, class: "img-thumbnail", width: 100, height: 100 %></td>
          <td>
          <%= link_to "Editar", edit_engine_path(engine), class:"btn btn-warning" %>
          <%= link_to "Ver", engine_path(engine), class:"btn btn-success" %>
          <%= link_to "Eliminar",engine, method: :delete, data: { confirm: "¿Estás seguro?" }, class:"btn btn-danger" %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to "Nuevo motor", new_engine_path, class:"btn btn-primary"  %>
  </p>
</div>

<%= raw pagy_nav(@pagy) %>

app/views/engines/new.html.erb
<%= form_with(model: @engine, local: true) do |form| %>
  <% if @engine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
        <% @engine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :type_engine, style: "display: block" %>
    <%= form.text_field :type_engine %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/engines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @engine %>

<div>
  <%= link_to "Edit", edit_engine_path(@engine), class:"btn btn-warning" %> |
  <%= link_to "Volver", engines_path, class:"btn btn-success" %>

  <%= button_to "Eliminar", @engine, method: :delete, class:"btn btn-danger" %>
</div>