config/routes.rb
Rails.application.routes.draw do
  get 'pages/terminos', to: 'pages#terminos', as: 'pages_terminos'
  resources :maintenances
  resources :engines
  get 'pages/inicio', to: 'pages#inicio', as: 'pages_inicio'
  resources :maintenances, only: [:show]

  devise_for :users

  # Define la ruta de inicio después de iniciar sesión
  authenticated :user do
    root 'pages#inicio', as: :authenticated_root
  end
  
  # Define la ruta de inicio predeterminada para los no autenticados (inicio de sesión)
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/views/shared/_footer.html.erb
<footer class="bg-dark text-light py-3">
    <div class="container">
        <div class="row">
        <div class="col-md-6 text-center">
            <p>&copy; 2023 Nicole Campos Chandía. Todos los derechos reservados.</p>
        </div>

    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-light">
    <div class="container-fluid">
            <div class="rounded-circle overflow-hidden" style="width: 40px; height: 40px;">
                <%= image_tag('logo.png', alt: 'JetMaintain', class: 'img-fluid') %>
            </div>
        <span class="navbar-brand">JetMaintain</span>
        <%= link_to 'Inicio', pages_inicio_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Termininos', pages_terminos_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Mantenimiento', maintenances_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Motores', engines_path, class: 'nav-link text-white' %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <% if user_signed_in? %>
                            <% if current_user.email.present? %>
                                Bienvenid@! <%= current_user.email %>
                            <% else %>
                                Hola! <%= current_user.email %>
                            <% end %>
                        <% else %>
                            Registrate o conectate
                        <% end %>
                    </a>
                    <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                        <% else %>
                            <li><%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'%></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>