config/routes.rb
Rails.application.routes.draw do
  get 'pages/terminos', to: 'pages#terminos', as: 'pages_terminos'
  resources :maintenances
  resources :engines
  get 'pages/inicio', to: 'pages#inicio', as: 'pages_inicio'
  resources :maintenances, only: [:show]

  devise_for :users

  # Define la ruta de inicio después de iniciar sesión
  authenticated :user do
    root 'pages#inicio', as: :authenticated_root
  end
  
  # Define la ruta de inicio predeterminada para los no autenticados (inicio de sesión)
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
    belongs_to :engine
    belongs_to :type_maintenance
    belongs_to :material
    belongs_to :town
    belongs_to :user
end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :authenticate_user!
  before_action only: [:new, :create] do
    authorize_request(["operator", "admin"])
  end
  before_action only: %i[ show edit update destroy ] do
    authorize_request(["admin"])
  end
# Define un método para autorizar al usuario
def authorize_user
  # Verifica el rol del usuario y autoriza en consecuencia
  if current_user.admin?
    # Admin tiene acceso completo
    return true
  elsif current_user.operador? && action_name == "create"
    # Operador solo tiene acceso a la acción "create"
    return true
  else
    # Los demás no tienen acceso
    redirect_to pages_inicio_path, alert: "Acceso denegado."
  end
end

before_action :authorize_user, only: [:create, :new]
  #before_action :set_maintenance, only: %i[ show edit update destroy ]

  # GET /maintenances or /maintenances.json
  def index
    @maintenances = Maintenance.all
    @pagy, @maintenances = pagy(@maintenances)
  end

  # GET /maintenances/1 or /maintenances/1.json
  def show
    @maintenance = Maintenance.find(params[:id])
  end

  # GET /maintenances/new
  def new
    @maintenance = Maintenance.new
    render "new"
  end

  # GET /maintenances/1/edit
  def edit
    @maintenance = Maintenance.find(params[:id])
  end

  # POST /maintenances or /maintenances.json
  def create
    @maintenance = Maintenance.new(maintenance_params)

    # Busca los registros relacionados en las tablas
    engine = Engine.find(params[:maintenance][:engine_id])
    type_maintenance = TypeMaintenance.find(params[:maintenance][:type_maintenance_id])
    town = Town.find(params[:maintenance][:town_id])
    material = Material.find(params[:maintenance][:material_id])


    # Asocia los registros relacionados con la Maintenance
    @maintenance.engine = engine
    @maintenance.type_maintenance = type_maintenance
    @maintenance.town = town
    @maintenance.material = material

    # Asocia el usuario actualmente autenticado
    @maintenance.user = current_user

    respond_to do |format|
      if @maintenance.save
        format.html { redirect_to maintenance_url(@maintenance), notice: "Maintenance was successfully created." }
        format.json { render :show, status: :created, location: @maintenance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenances/1 or /maintenances/1.json
  def update
    respond_to do |format|
      if @maintenance.update(maintenance_params)
        format.html { redirect_to maintenance_url(@maintenance), notice: "Maintenance was successfully updated." }
        format.json { render :show, status: :ok, location: @maintenance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenances/1 or /maintenances/1.json
  def destroy
    @maintenance = Maintenance.find(params[:id]) # Encuentra el mantenimiento por su ID

    if @maintenance.destroy
      respond_to do |format|
        format.html { redirect_to maintenances_url, notice: "Maintenance was successfully destroyed." }
      end
    else
      # Manejar el caso en el que el mantenimiento no pudo ser eliminado
      respond_to do |format|
        format.html { redirect_to maintenances_url, alert: "Unable to destroy maintenance." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance
      @maintenance = Maintenance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_params
      params.require(:maintenance).permit(:name_engine, :email, :engine_id, :type_maintenance_id, :town_id, :material_id)
    end
end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/views/maintenances/_form.html.erb
<%= form_with(model: @maintenance, local: true) do |form| %>
  <!-- Tipo de motor (engine) -->
  <div class="field">
    <%= form.label :engine_id, "Tipo de motor" %>
    <%= form.collection_select :engine_id, Engine.all, :id, :type_engine, prompt: "Selecciona un tipo de motor" %>
  </div>

  <!-- Tipo de mantenimiento (type_maintenance) -->
  <div class="field">
    <%= form.label :type_maintenance_id, "Tipo de mantenimiento" %>
    <%= form.collection_select :type_maintenance_id, TypeMaintenance.all, :id, :name, prompt: "Selecciona un tipo de mantenimiento" %>
  </div>

  <!-- Nombre del motor (engine) -->
  <div class="field">
    <%= form.label :name_engine, "Nombre del motor" %>
    <%= form.text_field :name_engine %>
  </div>

  <!-- Ciudad (town) -->
  <div class="field">
    <%= form.label :town_id, "Ciudad" %>
    <%= form.collection_select :town_id, Town.all, :id, :name, prompt: "Selecciona una ciudad" %>
  </div>

  <!-- Material (material) -->
  <div class="field">
    <%= form.label :material_id, "Material" %>
    <%= form.collection_select :material_id, Material.all, :id, :name, prompt: "Selecciona un material" %>
  </div>

  <!-- Email del usuario autenticado -->
  <div class="field">
    <%= form.label :email, "Email del usuario" %>
    <%= form.text_field :email, value: current_user.email, disabled: true %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Mantenimiento" %>
  </div>
<% end %>

app/views/maintenances/_maintenance.html.erb
<div id="<%= dom_id maintenance %>">
  <p>
    <strong>Name engine:</strong>
    <%= maintenance.name_engine %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= maintenance.photo %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= maintenance.email %>
  </p>

</div>

app/views/maintenances/edit.html.erb
<h1>Editar mantenimiento</h1>

<%= render "form", maintenance: @maintenance %>

<br>

<div>
  <%= link_to "ver", maintenance_path(@maintenance) %> |
  <%= link_to "Volver", maintenances_path %>
</div>

app/views/maintenances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center" >Mantenciones</h1>

<table class="table bg-danger">
  <thead>
    <tr>
      <th>Tipo de motor</th>
      <th>Tipo de mantenimiento</th>
      <th>Nombre del motor</th>
      <th>Foto</th>
      <th>Menu</th>
    </tr>
  </thead>
  <tbody>
    <% @maintenances.each do |maintenance| %>
      <tr>
        <td><%= maintenance.engine.type_engine %></td>
        <td><%= maintenance.type_maintenance.name %></td>
        <td><%= maintenance.name_engine %></td>
        <td><%= image_tag maintenance.engine.photo, class: "img-thumbnail",width: 100, height: 100 %></td> 
        <td>
          <%= link_to "Editar", edit_maintenance_path(maintenance), class:"btn btn-warning" %>
          <%= link_to "Ver", maintenance_path(maintenance), class:"btn btn-success" %>
          <%= link_to "Eliminar", maintenance, method: :delete, data: { confirm: "¿Estás seguro?" }, class:"btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= raw pagy_nav(@pagy) %>
<br>
<%= link_to "Nueva Mantención", new_maintenance_path, class: "btn btn-primary" %>
<br>

app/views/maintenances/new.html.erb
<h1>Nueva mantencion</h1>

<%= render "form", maintenance: @maintenance %>

<br>

<div>
  <%= link_to "Volver a mantenciones", maintenances_path %>
</div>

app/views/maintenances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @maintenance %>

<div>
  <%= link_to "Editare", edit_maintenance_path(@maintenance) %> |
  <%= link_to "Volver", maintenances_path %>

  <%= button_to "Eliminar mantenimiento", @maintenance, method: :delete %>
</div>